name: zdun
version: 2.0.0
github: "githubuser/zdun"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2026 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/zdun#readme>

dependencies:
  - base >= 4.7 && < 5
  - time

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings
  - ScopedTypeVariables
  - NumericUnderscores
  - BlockArguments

library:
  source-dirs: src
  dependencies:
    - network
    - async
    - http-client
    - http-client-tls
    - http-types
    - regex-tdfa
    - bytestring
    - text
    - optparse-applicative
    - unix
    - mtl

executables:
  zdun-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - zdun

tests:
  zdun-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - zdun
      - hspec
      - QuickCheck
      - network
      - bytestring
      - text
      - http-client
      - http-client-tls
    build-tools:
      - hspec-discover
